import Head from "next/head";
import styles from "@styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={styles.container}>
          <div className={`${styles.background_circle} ${styles.background_circle_blue}`}></div>
          <div className={`${styles.background_circle} ${styles.background_circle_red}`}></div>
          <div className={styles.glass_container}>
            <span className={styles.container_text}> This website is powered by Next.js </span>
            <p>
              You are on the wrong page. Go to <a href="/api/repo" className={styles.button_link}>/api/repo</a> for the card
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
