const COMMITS_TO_REQUEST = 3;
const TRUNCATE_CHAR_THRESHOLD = 50;
const GITHUB_USERNAME = 'saphalpdyl';
const SORT_BY = 'pushed';

export {
  COMMITS_TO_REQUEST,
  TRUNCATE_CHAR_THRESHOLD,
  GITHUB_USERNAME,
  SORT_BY
}
